logging:
  version: 1
  formatters:
    default:
      format: "%(asctime)s %(name)s %(threadName)s %(filename)s:%(lineno)d %(levelname)-8s %(message)s"
      datefmt: '%Y-%m-%d %H:%M:%S'
    metrics:
      format: "%(message)s"
  handlers:
    stdout:
      class: 'logging.StreamHandler'
      level: 'DEBUG'
      formatter: 'default'
      stream: 'ext://sys.stdout'
    stderr:
      class: 'logging.StreamHandler'
      level: 'ERROR'
      formatter: 'default'
      stream: 'ext://sys.stderr'
    file:
      class: 'logging.FileHandler'
      formatter: 'default'
      filename: 'logs/log.log'
      mode: 'w'
  loggers:
    src:
      level: 'DEBUG'
      handlers:
        stdout
        stderr
        file
    metrics:
      level: 'DEBUG'
      location: './results'